# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d8a85c183466b9954dfbd60d06e96f443ced5615f51a951be9533c22b7f8864bcfe52e6e5e7ba0b4b67346922f3319ffda2430b68b657aeb716288c7b9065a3

test:
  secret_key_base: 748a9f87ba4060639e55a4a796b8d6474cba575dd0ec110d20af96beec0a734ed25c5ca8436314118d0402df3feb031807ff1ece4907f09abbc06d14cebc12a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
